dist: focal
language: python
python:
- '3.8'
- '3.9'
matrix:
  fast_finish: true
env:
  - TOX_JOB="lint"
  - TOX_JOB="typecheck"
  - TOX_JOB="test"
install:
- pip install -U pip setuptools
- pip install tox-travis
script:
- tox
